hash-format = "sha256"

[[files]]
file = "config/yosbr/config/Spectrum.json5"

[[files]]
file = "config/yosbr/config/bclib/client.json"

[[files]]
file = "config/yosbr/config/soulbound.json"

[[files]]
file = "config/yosbr/config/universal-graves/config.json"

[[files]]
file = "kubejs/README.txt"

[[files]]
file = "kubejs/config/common.properties"

[[files]]
file = "kubejs/data/c/tags/items/copper_nuggets.json"

[[files]]
file = "kubejs/data/powah/loot_tables/blocks/deepslate_uraninite_ore.json"

[[files]]
file = "kubejs/data/powah/loot_tables/blocks/deepslate_uraninite_ore_dense.json"

[[files]]
file = "kubejs/data/powah/loot_tables/blocks/deepslate_uraninite_ore_poor.json"

[[files]]
file = "kubejs/data/powah/loot_tables/blocks/uraninite_ore.json"

[[files]]
file = "kubejs/data/powah/loot_tables/blocks/uraninite_ore_dense.json"

[[files]]
file = "kubejs/data/powah/loot_tables/blocks/uraninite_ore_poor.json"

[[files]]
file = "kubejs/server_scripts/example.js"

[[files]]
file = "kubejs/server_scripts/pulverizing.js"

[[files]]
file = "kubejs/startup_scripts/example.js"

[[files]]
file = "mods/ad-astra.pw.toml"
metafile = true

[[files]]
file = "mods/additional-structures.pw.toml"
metafile = true

[[files]]
file = "mods/advanced-networking.pw.toml"
metafile = true

[[files]]
file = "mods/ae2-emi-crafting.pw.toml"
metafile = true

[[files]]
file = "mods/ae2.pw.toml"
metafile = true

[[files]]
file = "mods/ae2cc.pw.toml"
metafile = true

[[files]]
file = "mods/affectionate.pw.toml"
metafile = true

[[files]]
file = "mods/airbag-1.1.1+1.20.1.jar"

[[files]]
file = "mods/almost-unified.pw.toml"
metafile = true

[[files]]
file = "mods/amarite.pw.toml"
metafile = true

[[files]]
file = "mods/amecs.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/applied-energistics-2-wireless-terminals.pw.toml"
metafile = true

[[files]]
file = "mods/arch-ex.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/argonauts.pw.toml"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
metafile = true

[[files]]
file = "mods/aurorasdecorations.pw.toml"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
metafile = true

[[files]]
file = "mods/automobility.pw.toml"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
metafile = true

[[files]]
file = "mods/bclib.pw.toml"
metafile = true

[[files]]
file = "mods/better-enchantment-boosting.pw.toml"
metafile = true

[[files]]
file = "mods/better-log4j-config.pw.toml"
metafile = true

[[files]]
file = "mods/betterend.pw.toml"
metafile = true

[[files]]
file = "mods/betternether.pw.toml"
metafile = true

[[files]]
file = "mods/bewitchment.pw.toml"
metafile = true

[[files]]
file = "mods/biome-makeover.pw.toml"
metafile = true

[[files]]
file = "mods/bits-and-chisels.pw.toml"
metafile = true

[[files]]
file = "mods/blahaj.pw.toml"
metafile = true

[[files]]
file = "mods/blossomlib.pw.toml"
metafile = true

[[files]]
file = "mods/blossompvp.pw.toml"
metafile = true

[[files]]
file = "mods/blur-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
metafile = true

[[files]]
file = "mods/bosses-of-mass-destruction.pw.toml"
metafile = true

[[files]]
file = "mods/botania.pw.toml"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
metafile = true

[[files]]
file = "mods/bovines-and-buttercups.pw.toml"
metafile = true

[[files]]
file = "mods/building-wands.pw.toml"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/cadmus.pw.toml"
metafile = true

[[files]]
file = "mods/calibrated.pw.toml"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/cccbridge.pw.toml"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
metafile = true

[[files]]
file = "mods/cinderscapes.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/conjuring.pw.toml"
metafile = true

[[files]]
file = "mods/consistencyplus.pw.toml"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/coxinha-utilities.pw.toml"
metafile = true

[[files]]
file = "mods/crawl.pw.toml"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
metafile = true

[[files]]
file = "mods/ct-overhaul-village.pw.toml"
metafile = true

[[files]]
file = "mods/ctov-farmers-delight-compat.pw.toml"
metafile = true

[[files]]
file = "mods/ctov-villagers-plus-compat.pw.toml"
metafile = true

[[files]]
file = "mods/dankstorage-1.20.1-4.6+dev.kneelawk.jar"

[[files]]
file = "mods/dark-enchanting.pw.toml"
metafile = true

[[files]]
file = "mods/dark-utilities.pw.toml"
metafile = true

[[files]]
file = "mods/dawn.pw.toml"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
metafile = true

[[files]]
file = "mods/decomod.pw.toml"
metafile = true

[[files]]
file = "mods/diggus-maximus.pw.toml"
metafile = true

[[files]]
file = "mods/durabilityviewer.pw.toml"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
metafile = true

[[files]]
file = "mods/emi-enchanting.pw.toml"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/emiffect.pw.toml"
metafile = true

[[files]]
file = "mods/emitrades.pw.toml"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/essential-commands.pw.toml"
metafile = true

[[files]]
file = "mods/exordium.pw.toml"
metafile = true

[[files]]
file = "mods/expanded-delight.pw.toml"
metafile = true

[[files]]
file = "mods/expanded-storage.pw.toml"
metafile = true

[[files]]
file = "mods/extended-drawers.pw.toml"
metafile = true

[[files]]
file = "mods/extra-mod-integrations.pw.toml"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/fastload.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
metafile = true

[[files]]
file = "mods/fwaystones.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/goml-reserved.pw.toml"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
metafile = true

[[files]]
file = "mods/heracles.pw.toml"
metafile = true

[[files]]
file = "mods/icyincitement.pw.toml"
metafile = true

[[files]]
file = "mods/immersive-structures-ii.pw.toml"
metafile = true

[[files]]
file = "mods/immersive-structures.pw.toml"
metafile = true

[[files]]
file = "mods/indium-1.0.21-dev.a22b8e8+mc1.20.1.jar"

[[files]]
file = "mods/industrial-revolution.pw.toml"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
metafile = true

[[files]]
file = "mods/jump-over-fences.pw.toml"
metafile = true

[[files]]
file = "mods/keybind-fix.pw.toml"
metafile = true

[[files]]
file = "mods/kibe.pw.toml"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
metafile = true

[[files]]
file = "mods/led.pw.toml"
metafile = true

[[files]]
file = "mods/lighty.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/loadingscreentips.pw.toml"
metafile = true

[[files]]
file = "mods/lootjs.pw.toml"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
metafile = true

[[files]]
file = "mods/lovely_snails.pw.toml"
metafile = true

[[files]]
file = "mods/luckperms.pw.toml"
metafile = true

[[files]]
file = "mods/mealapi.pw.toml"
metafile = true

[[files]]
file = "mods/mega.pw.toml"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
metafile = true

[[files]]
file = "mods/merequester.pw.toml"
metafile = true

[[files]]
file = "mods/mes-moogs-end-structures.pw.toml"
metafile = true

[[files]]
file = "mods/milk_plus.pw.toml"
metafile = true

[[files]]
file = "mods/minecells.pw.toml"
metafile = true

[[files]]
file = "mods/missing-wilds.pw.toml"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
metafile = true

[[files]]
file = "mods/mod-loading-screen.pw.toml"
metafile = true

[[files]]
file = "mods/modern-dynamics.pw.toml"
metafile = true

[[files]]
file = "mods/modern-industrialization.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/moogs-voyager-structures.pw.toml"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/mouse-wheelie.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
metafile = true

[[files]]
file = "mods/now-playing.pw.toml"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
metafile = true

[[files]]
file = "mods/peculiarpieces.pw.toml"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
metafile = true

[[files]]
file = "mods/peripheralium.pw.toml"
metafile = true

[[files]]
file = "mods/piercingpaxels.pw.toml"
metafile = true

[[files]]
file = "mods/pig-pen-cipher.pw.toml"
metafile = true

[[files]]
file = "mods/pineapple-mod.pw.toml"
metafile = true

[[files]]
file = "mods/plant-in-a-jar.pw.toml"
metafile = true

[[files]]
file = "mods/plethora-peripherals.pw.toml"
metafile = true

[[files]]
file = "mods/plushables.pw.toml"
metafile = true

[[files]]
file = "mods/pollinators-paradise.pw.toml"
metafile = true

[[files]]
file = "mods/powah.pw.toml"
metafile = true

[[files]]
file = "mods/power-networks.pw.toml"
metafile = true

[[files]]
file = "mods/promenade.pw.toml"
metafile = true

[[files]]
file = "mods/prometheus.pw.toml"
metafile = true

[[files]]
file = "mods/qkl.pw.toml"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
metafile = true

[[files]]
file = "mods/quilt-loading-screen.pw.toml"
metafile = true

[[files]]
file = "mods/rainglow.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/repurposed-structures-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/revelationary.pw.toml"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
metafile = true

[[files]]
file = "mods/runelic.pw.toml"
metafile = true

[[files]]
file = "mods/sandwichable.pw.toml"
metafile = true

[[files]]
file = "mods/scarves.pw.toml"
metafile = true

[[files]]
file = "mods/scriptor-magicae.pw.toml"
metafile = true

[[files]]
file = "mods/seamless-loading-screen.pw.toml"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
metafile = true

[[files]]
file = "mods/servertick.pw.toml"
metafile = true

[[files]]
file = "mods/show-me-what-you-got.pw.toml"
metafile = true

[[files]]
file = "mods/show-me-your-skin.pw.toml"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/softer-pastels.pw.toml"
metafile = true

[[files]]
file = "mods/soulbound-enchantment.pw.toml"
metafile = true

[[files]]
file = "mods/soulice.pw.toml"
metafile = true

[[files]]
file = "mods/spectrum-1.7.2-deeper-down-1.7.2-dev-3296def.jar"

[[files]]
file = "mods/stackdeobf.pw.toml"
metafile = true

[[files]]
file = "mods/styled-chat.pw.toml"
metafile = true

[[files]]
file = "mods/styled-nicknames.pw.toml"
metafile = true

[[files]]
file = "mods/styledplayerlist.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/tablesaw.pw.toml"
metafile = true

[[files]]
file = "mods/techreborn.pw.toml"
metafile = true

[[files]]
file = "mods/tempad.pw.toml"
metafile = true

[[files]]
file = "mods/templates-2.pw.toml"
metafile = true

[[files]]
file = "mods/terrestria.pw.toml"
metafile = true

[[files]]
file = "mods/the-graveyard-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/travelers-titles.pw.toml"
metafile = true

[[files]]
file = "mods/travelersbackpack.pw.toml"
metafile = true

[[files]]
file = "mods/traverse.pw.toml"
metafile = true

[[files]]
file = "mods/tree-hollows.pw.toml"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
metafile = true

[[files]]
file = "mods/turtlematic.pw.toml"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
metafile = true

[[files]]
file = "mods/universal-shops.pw.toml"
metafile = true

[[files]]
file = "mods/unlimitedperipheralworks.pw.toml"
metafile = true

[[files]]
file = "mods/utility-belt.pw.toml"
metafile = true

[[files]]
file = "mods/villagersplus.pw.toml"
metafile = true

[[files]]
file = "mods/when-dungeons-arise.pw.toml"
metafile = true

[[files]]
file = "mods/wiredredstone.pw.toml"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/yeet.pw.toml"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
metafile = true
